Baezon/pof-tools

- src/main.rs
On win 7 apparently, defining an "in" vec in the shader but not providing it will crash glium.
> Fix a bug with mismatched shaders vs provided normals

- pof/rustfmt.toml
- src/main.rs
- src/primitives.rs
I actually read the documentation, and found the `once_cell::sync::Lazy` type which is a better match for lazy statics than using `OnceCell` directly. Also the `OnceCell` used in the panic handler can be replaced by a channel to avoid needing a global.
Also fixes a few unused item warnings and the rustfmt.toml file in `pof/`.
> remove OnceCell

- src/ui.rs
Otherwise blanks out the rest of the properties panel. Still not sure this is the best way to do it, but it properly 'un-colors' and doesnt break the UI.
> Fix reset_widget_color

- Cargo.lock
- pof/Cargo.toml
- pof/src/parse.rs
- pof/src/types.rs
- pof/src/write.rs
- src/ui.rs
Adds support for lots of ancient versions which appear in the FSO parser and/or POF documentation. (I think it would be fine to drop support for really old versions with no extant POF files, but only if FSO also drops support.) Also replaces `.unwrap()` with `?` for all IO errors in parsing.
Also there are a few version checks that did not match the [wiki description](https://wiki.hard-light.net/index.php/POF_data_structure), this should be fixed.
> add old version handling, fewer IO unwraps

- pof/src/types.rs
- src/ui.rs
fixes #43
Also simplified the loop of `get_total_subobj_offset` and fixed a typo.
> include vertex offsets in bbox calculation

- src/main.rs
It would also be nice to set up the logger to print to stderr in addition to writing to the log.
FYI I hit this error while reading the [bromios](https://www.hard-light.net/forums/index.php?topic=97850.0) model:
```rust
Failed to load texture bromios.dds:
Unsupported(UnsupportedError { format: Exact(Dds), kind: GenericFeature("DDS FourCC [68, 88, 49, 48]") })
```
> log texture loading errors instead of crashing

- pof/src/types.rs
- src/main.rs
- src/ui.rs
- src/ui_properties_panel.rs
Turn all the fields in properties into explicit fields and 'hide' the raw text manipulation of properties... for all but subobjects, because they're by far the most complicated.
> Introduce new properties handling

- pof/src/parse.rs
- pof/src/types.rs
- pof/src/write.rs
- src/main.rs
- src/ui_properties_panel.rs
some minor tweaks discovered from reading an ancient POF parser. Relevantly, turrets, gunpoints and eyepoint normals must be normalized (or at least, nonzero). Since we already have eager normalization in dockpoints it seems consistent to do the same with these normals. (Glowpoint normals are *not* similarly asserted to be nonzero, although I believe the reason is because they are `Option<NormalVec3>`: they are either normalized or zero.)
> normalize turret/gunpoint/eyepoint normals

- src/main.rs
- src/ui.rs
The logic of `GlBufferedObject::new` has been split into more functions to avoid duplication, although all the new types and functions can be scoped to within `GlObjectBuffers::new` (I didn't like the indentation depth of doing so, so I left them as top level functions,) Also the algorithm is more efficient than before on entirely triangle data, for which the non-triangulated wireframe doesn't need to be constructed because you can just use the normal index buffer directly (which is what it was doing before). There is some added complication to lazily initialize the wireframe object since we don't know in advance whether a mesh is triangulated or not. (Maybe this should be a flag? It is easy to detect on parse and in some modes we just directly know the answer.)
> feat: don't triangulate wireframe

- pof/src/parse.rs
- pof/src/types.rs
- src/main.rs
Move `transpose` and `inverse` out of the shader so we can support more setups.
Also a small shield parsing fix.
> Make shaders more permissive

- pof/src/parse.rs
- pof/src/types.rs
- pof/src/write.rs
- src/main.rs
Since we are planning to drop these vestigial fields in #36 and the current code does not generate `plane_normal` and `plane_point` fields during recalculate anyway, remove these from the data structure and always produce the zero vector in these fields (except for polygon center which is recalculated on the spot on write). This regresses round-tripping for old POF versions, since these fields will no longer be preserved, but we are dropping them from the format because they are unused in the first place.
> remove Polygon.center and calculate it on the fly

- pof/src/types.rs
`PolyVertex<()>`, used only by insignia, do not write norm ids at all.
> Dont write normal id for no norm polyvertex

- pof/src/parse.rs
- pof/src/types.rs
Turret point transform should be based on the current object, not just its parent and default turrets should not have any fire points.
> Fix some turret bugs

- pof/src/parse.rs
Well, we know it happens now, so let's not make it a show-stopper. Worth letting the user know about but for now stability is the bigger concern.
Fixes #76
> Dont assert on non-zero uv sets

- pof/src/types.rs
- src/main.rs
- src/ui_properties_panel.rs
Gotta rebuild the buffers for all recursive children. Also add `do_for_recursive_subobj_children()` and some visual tweaks to the transform window
> Fix a bug with children of transformed objects

- pof/src/parse.rs
- pof/src/types.rs
- src/main.rs
- src/ui.rs
- src/ui_properties_panel.rs
Probably should have been broken into several PRs, but they have the common thread of 'coloring the tree values' so they came together. `TreeSelection` renamed to `TreeValue`, warnings/errors moved into pof crate, displayed warnings/errors are now links to their respective problem object, and destroyed/debris/detail objects are displayed in the subobject properties panel containing links to each other.
> Overhaul warnings, and do semantic name linking

- pof/src/types.rs
...instead of turrets <-> turrets. This allows for importing a model with turrets onto one without turrets, provided their subobjects still match up.
> Import turrets by direct objects

- pof/src/types.rs
Turns out while some places have it optional, others require it. Easiest to simply always put one there if there isn't already.
> Always ensure a $ on special point names

- src/main.rs
The pof expects global coordinates, and the coordinates will display global as well, so don't visually display the docks relative to their parent. I tried making the coordinates local, instead of the visuals global, but that was a big pita.
> Dont offset dock points for parent submodel

- pof/src/parse.rs
Better error message for malformed gltf files
> No Default Scene error message for GLTF parsing.

- pof/src/parse.rs
We know PCS2 can make models like this, and Pof tools can run it no problem and will always fix it.
> remove `parent out of order` assert

- pof/src/types.rs
Vertex normals are transformed, but I forgot the polygon normal. Since these are on the individual bsp leaves, it's easiest to just recalculate the entire thing, although this invovles cloning all the polygons... which is maybe bad? @digama0 help
> Ensure polygon normals are transformed too

- src/main.rs
Either just primary points, just secondary points, or both could be selected, and all 3 cases need to be handled. The `WeaponTreeValue::SecBankPoint(bank_idx - primary_banks, point_idx))))` case is only necessary if both are displayed, where the secondary bank indices are appended after the primary ones, otherwise the bank index should be used as is. Also for lollipop hovering purposes, the 3 cases also have to be separated. Can't hover things that aren't being displayed.
> Fix two bugs with secondary hovering

- src/main.rs
Ensures `tree_val_selection` is always sanitary.
> reset tree selection on model load

- pof/src/types.rs
- src/main.rs
- src/ui.rs
- src/ui_properties_panel.rs
Fixes a bug where they wouldn't be culled properly sometimes and now cycles through problem entries when you click on the warning/error.
> Fixes and improvements for dupe name warnings/errors

- src/main.rs
Follow-up for #134, `maybe_recalculate_3d_helpers()` is sensitive to a stale `tree_view_selection` so do it after thats been reset
> reset tree val before recalc helpers

- pof/src/parse.rs
PCS2 doesn't appear to inject a `-1` path num on a docking bay so it may be even older, not sure exactly what it means beyond a simple omission but it certainly isn't interpretable as a valid path.
> Filter out parsed -1 path nums on docking bays

- src/ui.rs
As `<unnamed>` rather than making a teensy hard to click button with empty string as the text.
> Display unnamed tree vals

- pof/src/parse.rs
- pof/src/types.rs
- pof/src/write.rs
- src/ui.rs
- src/ui_properties_panel.rs
`attached_subobj` is optional for eye points. Who knew!
> guard against no subobject eye points

- pof/src/parse.rs
- pof/src/types.rs
- src/main.rs
- src/ui.rs
- src/ui_properties_panel.rs
Add a warning for detail0 having a non-zero offset which can cause issues in FSO
Also add another sanitization check for obj ids for eye point attached objects.
> detail0 non zero offset warning

- pof/src/parse.rs
- src/ui.rs
- src/ui_properties_panel.rs
1. Prune textures with no polygons, these are useless
2. Use the first scene if theres no default scene in gltf
3. Extend the existing texture map when doing multiple merge textures operations
> Several bug fixes

- pof/src/types.rs
- src/ui_properties_panel.rs
If `transform_offset` is true, the matrix, including translation should apply to the subobject (line 2395). This ensures a header transform with translates will actually move all the top level objects, rather than merely rotate or scale.
> Small fix to header translating transformations

- pof/src/parse.rs
- pof/src/types.rs
- pof/src/write.rs
- src/main.rs
- src/ui.rs
- src/ui_import.rs
- src/ui_properties_panel.rs
Finally, a proper unified dialog for importing bits of another model into the currently opened model.
Sadly this requires some manual manipulation of parents and children so they couldn't stay totally private and go through their getters and setters anymore.
> Proper pof import

- pof/src/parse.rs
Checking validity of the path is to be done against the previously parsed list of actual paths, not the list of paths on this dockpoint, i.e. `paths` should not be referring to this local `paths`
> Fix accidental shadow with reading dock points

- src/ui_properties_panel.rs
This message should only appear if they've selected the 'Untextured' texture slot, but the `tex()` function will map `None`, no untextured slot, to the header tree value, erroneously displaying the message if the header is selected. Don't display if the untextured slot is None.
> Small fix for 'untextured' texture slot selection

- pof/src/parse.rs
#152 in addition to fixing the shadow also sanitizes invalid indices. We might not have actually parsed paths yet, and if not all would be claimed invalid. Just stuff them regardless and then sanitize after.
> Fix dock paths take 2

- src/ui_properties_panel.rs
Some errors relate to detail objects so recheck those too if detail objects change.
> Fix errors not being rechecked on detail objects change

- pof/src/types.rs
- pof/src/write.rs
1.  Make sure -1 is written for no subobj eye points, since the default serialize for options is to omit `None`.
2. Actually write a valid polygon "center" point for old pof versions. All it needs to be is on the plane, so any vert will do, but putting 0 *will* screw up these old pofs when used on old fso versions.
> Two small fixes

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- pof/src/parse.rs
- pof/src/types.rs
- pof/src/write.rs
- src/main.rs
- src/ui.rs
- src/ui_import.rs
- src/ui_properties_panel.rs
Supresses egui's built in text edit undo system by using `clear_undoer`. A subsequent PR will return undoing functionality through pof tools' system based on the model's data, not the egui widget's history.
Needed a new version for that function, so lots of updates came with.
> Lots of dependency updates and suppress egui undo
