- Cargo.lock
- pof/Cargo.toml
- pof/src/parse.rs
- pof/src/types.rs
- pof/src/write.rs
- rustfmt.toml
- src/main.rs
- src/ui.rs
> Fix panics

- pof/src/parse.rs
- pof/src/types.rs
Transforms need to be accumulated from parent nodes and percolated down into child nodes and combined with their own transforms.
> Use proper transforms on dae import

- pof/src/types.rs
- src/main.rs
- src/ui.rs
- src/ui_properties_panel.rs
...and add some errors and change the way parenting is handled by the pof crate.
> Allow for re-parenting

- pof/src/main.rs
- pof/src/parse.rs
- pof/src/types.rs
I've been assuming that's the case, so let's ensure it is.
> Ensure obj ids are indices

- pof/src/parse.rs
- pof/src/types.rs
- pof/src/write.rs
- src/ui.rs
- src/ui_properties_panel.rs
Parse and display them, but error on them.
> Handle large vert/norm counts

- pof/src/parse.rs
- src/ui.rs
The handling of the `Matrix(_)` transform subsumes all the other cases in `dae_parse_point`.
> remove buggy transform handling

- pof/src/parse.rs
- pof/src/write.rs
They are flipped on the... 'v'... axis.
> Fix dae import/export UVs

- pof/src/parse.rs
- pof/src/types.rs
- pof/src/write.rs
Added some more versions referenced in FSO.
> more prehistory, simplify recalculate_bboxes

- pof/src/parse.rs
- pof/src/types.rs
- src/ui_properties_panel.rs
Makes axis changes also affect the movement type. Fixes #64
> SubsysMovement{Axis,Type} cleanup

- src/main.rs
> Fix saving extension casing

- .gitignore
- pof/src/parse.rs
Fixes an accidental regression from #58
> Fix dae tex coords regression

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/ui.rs
- src/ui_properties_panel.rs
Tree values can now be separately expanded and selected, double click toggles expansion status, and using indexing buttons to switch between values also forces them open.
> Update egui and Add some qol improvements to collapsing tree values

- pof/src/write.rs
> flush NaN to 0 during glTF export

- pof/src/types.rs
- src/ui.rs
- src/ui_properties_panel.rs
> Add some subobject name related errors

- .github/workflows/ci.yml
- pof/src/types.rs
- src/main.rs
- src/ui.rs
This is explicitly a stop gap solution until a more featureful and straightforward version of importing arbitrary pof data can be implemented.
> Add pcs2 style global import

- pof/src/types.rs
- src/main.rs
- src/ui.rs
- src/ui_properties_panel.rs
And finally do `select_new_tree_val` like I've been intending. Also some formatting changes from #71 which i should probably look into.
> Properly display destroyed models

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/ui.rs
- src/ui_properties_panel.rs
Just applies to lollipop dragging and data vector manipulations atm, will add more later. Closes #6
> Add an undo system

- pof/src/types.rs
- src/main.rs
- src/ui_properties_panel.rs
Will want checkboxes later for if/how this should happen.
> Update pof data when transforming the header

- src/main.rs
A bunch of code that was accidentally being done per buffer object when it only needed to be done once.
> Fix performance bug

- pof/src/write.rs
...for some reason. Fixes an issue where position is not exported properly.
> Ensure gltf writes transposed matrices

- src/ui.rs
- src/ui_properties_panel.rs
There were some ideas to use empty string or something, but FSO has a few of these already so may as well recommend one of them.
> Suggest "invisible" for ignored textures

- Cargo.lock
- Cargo.toml
- README.md
- pof/Cargo.toml
to keep up with the dae-parser nalgebra version bump. Closes #124
> update nalgebra versions

- src/ui_properties_panel.rs
Follow-up for #116, scaling by 0 is bad but negative is ok.
> Negative scaling is ok

- pof/src/parse.rs
- src/main.rs
- src/ui.rs
- src/ui_properties_panel.rs
Also introduce  an indirection between pof tools' conception of 'the model' vs pof's, which will be useful.
> Allow for merging textures

- pof/src/parse.rs
- pof/src/write.rs
> Write and read translation axis in .dae and .gltf

- Cargo.lock
- pof/Cargo.toml
- pof/src/parse.rs
And log any that were discarded
> Sanitize debris and detail levels on parse

- pof/src/types.rs
- src/ui_properties_panel.rs
> Add recalculation of visual center

- src/ui.rs
- src/ui_properties_panel.rs
Add buttons to permanently the bounding box, radius and offset/center. Also rearrange a few things.
> Display bbox radius offset buttons

- src/ui_import.rs
For some reason I only put it on subobjects with children.
> make sure subobjects without children auto import too
